name: Deploy Staging to S3 Staging
on:
  push:
    branches:
    - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: sleavely/node-awscli:14.x
    steps:
    - uses: actions/checkout@v2
    - run: aws s3 sync . s3://demo.staging-tout-culture --acl public-read --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        AWS_REGION: ca-central-1 
        WEBHOSTING_BUCKET_NAME: demo.staging-tout-culture